language: cpp

addons:
  apt:
    packages:
    - gfortran
    - libhdf5-serial-dev
    - liblapack-dev
    - python-numpy
    - swig

matrix:
  include:
  - os: linux
  - os: osx
    env: CC="gcc-7 -fopenmp" CXX="g++-7 -fopenmp" CPPFLAGS=-I/usr/local/opt/openblas/include LDFLAGS=-L/usr/local/opt/openblas/lib BLAS_LIBS=-lopenblas 

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc --without-multilib         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install autoconf automake hdf5 openblas; fi

script:
  - ./autogen.sh --enable-shared --with-python --prefix=${HOME}/local
  - make install
  - PATH=${PATH}:${HOME}/local/bin:${HOME}/local/share/scuff-em/tests make check
  - find ${HOME}/local/lib
  - PYTHONPATH=${HOME}/local/lib/python2.7/site-packages python -c 'import scuff'

after_script:
  - for FILE in `find ${TRAVIS_BUILD_DIR} -name test-suite.log`; do printf "\n**${FILE}:\n"; cat ${FILE}; done
