site_name: SCUFF-EM documentation
site_author: Homer Reid
site_url: http://homerreid.github.io/scuff-em-documentation

repo_name: scuff-em
repo_url: https://github.com/homerreid/scuff-em/

theme:
     name:        'material'
     custom_dir:  'scuff-em-material-theme'
     language:    'en'
     logo:        'reference/scuffEMLogo.png'
     palette:
       primary:   'indigo'
       accent:    'indigo'
     font:
       text:      'Noto Sans'
       accent:    'Source Code Pro'
     feature:
       tabs:       true

markdown_extensions:
    - codehilite:
    - wikilinks
    - toc:
        title: Table of Contents
#        FirstH1: true
    - attr_list
    - mkdcomments
    - mdx_math:
        enable_dollar_delimiter: True
#    - pymdownx.highlight:
    - pymdownx.inlinehilite:
    - pymdownx.superfences:
#    - pymdownx.tasklist
    - markdown_include.include:
        base_path: docs

extra_javascript:
#    - 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML'
    - 'javascripts/MathJax.js?config=TeX-AMS_HTML'
    - 'javascripts/mathjaxhelper.js'

extra_css:
    - css/scuff-em.css

extra:
    disqus: 'homerreid-github-io-scuff-em-documentation.disqus.com'

google_analytics:
    - 'UA-119340518-1'
    - 'auto'

pages:

- 'index.md'

- Examples:
    - 'SCUFF-EM tutorial examples':               'examples/index.md'
    - 'Mie scattering':                           'examples/MieScattering/MieScattering.md'
    - 'Electrostatics of a spherical dielectric shell':   'examples/DielectricShell/DielectricShell.md'
    - 'Spatially-resolved study of plane-wave transmission through an infinite-area thin dielectric film':   'examples/ThinFilm/ThinFilm.md'
    - 'Imaging diffraction patterns of discs, disc arrays, and hole arrays in metal screens': 'examples/DiffractionPatterns/DiffractionPatterns.md'
    - 'Mode frequencies and field patterns of resonant modes in gold nanorods': 'examples/NanorodResonantModes/NanorodResonantModes.md'
    - 'Casimir forces in a compact geometry':     'examples/CubeTorus.md'
    - 'Casimir forces in a 1D extended geometry': 'examples/SiliconBeams/SiliconBeams.md'
    - 'Casimir forces in a 2D extended geometry': 'examples/SiliconSlabs/SiliconSlabs.md'
    - 'Casimir-Polder potentials in dielectric nanostructures': 'examples/NanostructureCasimirPolder/NanostructureCasimirPolder.md'
    - 'Thermal radiation, heat transfer, and non-equilibrium Casimir forces between silicon dioxide spheres': 'examples/SiO2Spheres/SiO2Spheres.md'
    - 'Spatial distribution of heat flux from a warm tip over a cold substrate': 'examples/TipSubstrate/TipSubstrate.md'
    - 'LDOS and dyadic Green functions above an infinite aluminum half-space': 'examples/HalfSpaceLDOS/HalfSpaceLDOS.md'
    - 'Electrostatic polarizability of platonic solids': 'examples/PlatonicSolids/PlatonicSolids.md'
    - 'Capacitance of two-body capacitors': 'examples/TwoBodyCapacitors/TwoBodyCapacitors.md'
    - 'Capacitance of a PCB stripline trace': 'examples/StriplineCapacitor/StriplineCapacitor.md'
    - 'Implicit handling of multilayer dielectric substrates': 'examples/ImplicitSubstrate/ImplicitSubstrate.md'
    - 'Finite-size effects in stripline capacitors': 'examples/pythonCapacitance/pythonCapacitance.md'
    - 'Electrostatic fields of an electrode array': 'examples/PaulTrap/PaulTrap.md'
    - 'Z-parameters and directivity of Yagi-Uda antennas': 'examples/YagiUdaAntennas/YagiUdaAntennas.md'
    - 'Input impedance, mutual coupling, and radiated fields of microstrip RF devices': 'examples/MicrostripDevices/MicrostripDevices.md'

- Test suite:
    - 'Overview of the test suite':                                        'tests/Overview.md'
    - 'Mie scattering':                                                    'tests/MieScattering/MieScattering.md'
    - 'Fresnel scattering':                                                'tests/FresnelScattering/FresnelScattering.md'
    - 'Equilibrium Casimir forces between spheres':                        'tests/CasimirSpheres/CasimirSpheres.md'
    - 'Equilibrium Casimir forces between plates':                         'tests/CasimirPlates/CasimirPlates.md'
    - 'Equilibrium Casimir-Polder potential near a sphere':                'tests/CPSphere/CPSphere.md'
    - 'Equilibrium Casimir-Polder potential near a plate':                 'tests/CPPlate/CPPlate.md'
    - 'Heat transfer and non-equilibrium Casimir forces between spheres':  'tests/NEQSpheres/NEQSpheres.md'
    - 'Low-level tests of the core library':                               'tests/libscuff/libscuff.md'

- General reference:
    - 'Top-level overview':             'reference/TopLevel.md'
    - 'Installation':                   'reference/Installing.md'
    - 'Geometry descriptions':          'reference/Geometries.md'
    - 'Equivalent edge/surface pairs':  'reference/EquivalentEdgeSurfacePairs.md'
    - 'Material designations':          'reference/Materials.md'
    - 'Geometric transformations':      'reference/Transformations.md'
    - 'Incident fields':                'reference/IncidentFields.md'
    - 'Brillouin zone integration':     'reference/BrillouinZoneIntegration.md'
    - 'FAQ':                            'reference/FAQ.md'

- Command-line tools:
    - 'General command-line reference': 'applications/GeneralReference.md'
    - 'scuff-scatter':         'applications/scuff-scatter/scuff-scatter.md'
    - 'scuff-transmission':    'applications/scuff-transmission/scuff-transmission.md'
    - 'scuff-ldos':            'applications/scuff-ldos/scuff-ldos.md'
    - 'scuff-tmatrix':         'applications/scuff-tmatrix/scuff-tmatrix.md'
    - 'scuff-cas3D':           'applications/scuff-cas3D/scuff-cas3D.md'
    - 'scuff-caspol':          'applications/scuff-caspol/scuff-caspol.md'
    - 'scuff-neq':             'applications/scuff-neq/scuff-neq.md'
    - 'scuff-rf':              'applications/scuff-rf/scuff-rf.md'
    - 'scuff-static':          'applications/scuff-static/scuff-static.md'
    - 'scuff-spectrum':        'applications/scuff-spectrum/scuff-spectrum.md'
    - 'scuff-analyze':         'applications/scuff-analyze/scuff-analyze.md'
    - 'scuff-integrate':       'applications/scuff-integrate/scuff-integrate.md'

- High-level interface:
    - 'High-Level Interface':  'HighLevelInterface/HighLevelInterface.md'

- Low-level API:
    - 'libscuff':              'API/libscuff.md'
    - 'MainFlow API':          'API/MainFlow.md'
    - 'Utility API':           'API/UtilityAPI.md'

- For developers:
    - 'Implementation':                        'forDevelopers/Implementation.md'
    - 'Data Structures':                       'forDevelopers/DataStructures.md'
    - 'Documentation':                         'forDevelopers/Documentation.md'
    - 'Code for computing singular integrals': 'forDevelopers/SingularIntegrals.md'
